Validate project image and inject secrets (#8)

diff --git a/.github/actions/import/action.yml b/.github/actions/import/action.yml
--- a/.github/actions/import/action.yml
+++ b/.github/actions/import/action.yml
@@ -15,14 +15,31 @@ inputs:
   management_key:
     description: 'The management key for the Descope project'
     required: true
+  secrets:
+    description: 'An optional JSON value with additional secrets to inject into the import data'
+    default: '[]'
   files_path:
     description: 'The path to the import files (i.e., the directory containing the environment.json file)'
     default: '.'
+  validate_only:
+    description: 'Whether to only perform the validate step'
+    type: boolean
+  import_only:
+    description: 'Whether to only perform the import step'
+    type: boolean
   descopecli_version:
     description: 'The version of the descopecli tool to use'
     default: 'v0.1.0'
   descope_base_url:
     description: 'The base URL used to communicate with Descope servers (for troubleshooting purposes)'
+
+outputs:
+  failure_file:
+    description: 'The path to a file with a list of failures, or empty if there were none'
+    value: ${{ steps.validate.outputs.failure_file }}
+  secrets_file:
+    description: 'The path to a JSON array with any missing secrets, or empty if there were none'
+    value: ${{ steps.validate.outputs.secrets_file }}
 
 runs:
   using: 'composite'
@@ -45,10 +62,10 @@ runs:
       shell: bash
       run: go install github.com/descope/descopecli@main
 
-    - name: Validate State
+    - name: Check State
       shell: bash
       run: |
-        echo "Validating action state"
+        echo "Checking action state"
         if [ -z "${{ inputs.project_id }}" ]; then
           echo "The project_id input is required for this action to run"
           exit 1
@@ -60,7 +77,7 @@ runs:
           exit 1
         fi
         if [ -z "${{ inputs.files_path }}" ]; then
-          echo "The files_path input is cannot be an empty string"
+          echo "The files_path input cannot be an empty string"
           exit 1
         fi
         if ! [ -d "${{ inputs.files_path }}" ]; then
@@ -68,11 +85,45 @@ runs:
           exit 1
         fi
 
+    - name: Validate Data
+      if: ${{ !inputs.import_only }}
+      id: validate
+      shell: bash
+      env:
+        DESCOPE_MANAGEMENT_KEY: ${{ inputs.management_key }}
+        DESCOPE_BASE_URL: ${{ inputs.descope_base_url }}
+      run: |
+        echo "Validating project data"
+        set +e
+        SECRETS_INPUT="$(mktemp)"
+        SECRETS_OUTPUT="$(mktemp)"
+        FAILURE_OUTPUT="$(mktemp)"
+        jq -r '.inputs.secrets' $GITHUB_EVENT_PATH > "$SECRETS_INPUT"
+        descopecli project validate "${{ inputs.project_id }}" --path "${{ inputs.files_path }}" --secrets-input "$SECRETS_INPUT" --secrets-output "$SECRETS_OUTPUT" --failure-output "$FAILURE_OUTPUT"
+        result=$?
+        rm "$SECRETS_INPUT"
+        if [ "$result" = "2" ]; then
+          if [ -f "$SECRETS_OUTPUT" ] && [ -s "$SECRETS_OUTPUT" ]; then
+            echo secrets_file="$SECRETS_OUTPUT" >> $GITHUB_OUTPUT
+          fi
+          if [ -f "$FAILURE_OUTPUT" ] && [ -s "$FAILURE_OUTPUT" ]; then
+            echo failure_file="$FAILURE_OUTPUT" >> $GITHUB_OUTPUT
+          fi
+        fi
+        exit $result
+
     - name: Import Project
+      if: ${{ !inputs.validate_only }}
       shell: bash
       env:
         DESCOPE_MANAGEMENT_KEY: ${{ inputs.management_key }}
         DESCOPE_BASE_URL: ${{ inputs.descope_base_url }}
       run: |
         echo "Importing project"
-        descopecli project import "${{ inputs.project_id }}" --path "${{ inputs.files_path }}"
+        set +e
+        SECRETS_INPUT="$(mktemp)"
+        jq -r '.inputs.secrets' $GITHUB_EVENT_PATH > "$SECRETS_INPUT"
+        descopecli project import "${{ inputs.project_id }}" --path "${{ inputs.files_path }}" --secrets-input "$SECRETS_INPUT"
+        result=$?
+        rm "$SECRETS_INPUT"
+        exit $result
